site_name: The Integrated Canine Data Commons Bioinformatics
site_url: https://cbiit.github.io/icdc-genomics/
site_description: >-
   </br></br>Select a tutorial and learn how to access data from the ICDC and perform a bioinformatic analysis



theme:
  name: readthedocs

nav:
  - Home: index.md
  - About: about.md
  - Tutorial: rna-seq.md
 
