site_name: The Integrated Canine Data Commons Bioinformatics Training Center
site_url: https://cbiit.github.io/icdc-bioinformatics/
repo_url: https://github.com/CBIIT/icdc-bioinformatics
site_description: >-
   </br></br>Select a tutorial and learn how to access data from the ICDC and perform a bioinformatic analysis

theme:
   name: material
   palette:
    primary: custom
   font:
      text: Arial
   logo: assets/canine_bubble.png
   favicon: images/canine_bubble.png
   icon: 
      repo: fontawesome/brands/github

   icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
   features:
      - navigation.path
      - navigation.sections
      - navigation.tabs
      - navigation.tracking
      - navigation.path
      - navigation.top
      - navigation.expand 
      - navigation.footer

#nav:
  #- Home: index.md
  #- About: about.md
  #- Tutorials: 
      #- RNA-Seq on the CGC: rna-seq.md

docs_dir: docs
extra_css:
  - stylesheets/extra.css
  - stylesheets/style.css

plugins:
   - search # must enable explicitly if there is a plugins block
   - awesome-pages # simplifies configuring page titles and their order https://pypi.org/project/mkdocs-awesome-pages-plugin/
   - open-in-new-tab
   - glightbox

edit_uri: ""

extra:
  hypothesis: true
  
  social:
   - icon: fontawesome/brands/twitter
     link: https://twitter.com/NCIDataSci
   - icon: fontawesome/solid/envelope
     link: mailto:icdchelpdesk@nih.gov>


markdown_extensions:
- admonition
- attr_list
- pymdownx.superfences
- pymdownx.tabbed:
   alternate_style: true

   
 
